version: '3.8'
services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - php
  php:
    build: ./php
    restart: always
    volumes:
      - "./web:/var/www/html"
      - "./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
  composer:
    image: "composer:2.3"
    volumes:
        - "./web:/app"
    command: install